export const GET_LIST_ACCOUNT = "GET_LIST_ACCOUNT";

export const GET_LIST_ACCOUNT_SUCCESS = "GET_LIST_ACCOUNT_SUCCESS";

export const GET_LIST_ACCOUNT_FAILED = "GET_LIST_ACCOUNT_FAILED";

export const SET_ISSUCCESS = "SET_ISSUCCESS";

export const REGESTER_ACCOUNT = "REGESTER_ACCOUNT";
export const REGESTER_ACCOUNT_SUCCESS = "REGESTER_ACCOUNT_SUCCESS";
export const REGESTER_ACCOUNT_FAILED = "REGESTER_ACCOUNT_FAILED";
export const GET_ACCOUNT = "GET_ACCOUNT";
