export const GET_LIST_QUESTION = "GET_LIST_QUESTION";

export const GET_LIST_QUESTION_SUCCESS = "GET_LIST_QUESTION_SUCCESS";

export const GET_LIST_QUESTION_FAILED = "GET_LIST_QUESTION_FAILED";

export const ADD_SELECT_QUESTION = "ADD_SELECT_QUESTION";

export const RESET_SELECT_QUESTION = "RESET_SELECT_QUESTION";

export const STOP_TIME = "STOP_TIME";
export const RESET_STOP_TIME = "RESET_STOP_TIME";

export const GET_TIME_OUT = "GET_TIME_OUT";
export const RESET_TIME_OUT = "RESET_TIME_OUT";
